<a href="https://colab.research.google.com/github/biswa2005/ML-Learning/blob/main/Classification_Algorithms.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = sns.load_dataset('titanic')
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [3]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [4]:
df.drop(columns=['who', 'adult_male', 'deck', 'embark_town', 'class', 'alive'], inplace=True)

In [5]:
df['age'].fillna(df['age'].mean(), inplace=True)

In [6]:
df.dropna(subset=['embarked'], inplace=True)

In [7]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  alone
0         0       3    male  22.0      1      0   7.2500        S  False
1         1       1  female  38.0      1      0  71.2833        C  False
2         1       3  female  26.0      0      0   7.9250        S   True
3         1       1  female  35.0      1      0  53.1000        S  False
4         0       3    male  35.0      0      0   8.0500        S   True

In [8]:
df = pd.get_dummies(data=df, dtype='int64', drop_first=True)
df.head()

survived  pclass   age  sibsp  parch     fare  alone  sex_male  embarked_Q  \
0         0       3  22.0      1      0   7.2500  False         1           0   
1         1       1  38.0      1      0  71.2833  False         0           0   
2         1       3  26.0      0      0   7.9250   True         0           0   
3         1       1  35.0      1      0  53.1000  False         0           0   
4         0       3  35.0      0      0   8.0500   True         1           0   

   embarked_S  
0           1  
1           0  
2           1  
3           1  
4           1

In [9]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [10]:
X = df.drop("survived", axis=1)
y = df["survived"]

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [12]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

###Logistic Regression

In [13]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(X_train_scaled, y_train)

LogisticRegression()

In [14]:
y_pred = model.predict(X_test_scaled)

In [15]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [16]:
accuracy_score(y_test, y_pred)

0.8089887640449438

In [17]:
confusion_matrix(y_test, y_pred)

array([[93, 16],
       [18, 51]])

In [18]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.84      0.85      0.85       109
           1       0.76      0.74      0.75        69

    accuracy                           0.81       178
   macro avg       0.80      0.80      0.80       178
weighted avg       0.81      0.81      0.81       178



###KNN (K-Nearest Neighbor)

In [19]:
from sklearn.neighbors import KNeighborsClassifier

In [20]:
knn_model = KNeighborsClassifier(n_neighbors = 5)
knn_model.fit(X_train_scaled, y_train)

KNeighborsClassifier()

In [21]:
y_pred_knn = knn_model.predict(X_test_scaled)

In [22]:
accuracy_score(y_test,y_pred_knn)

0.7865168539325843

In [33]:
confusion_matrix(y_test, y_pred_knn)

array([[88, 21],
       [17, 52]])

In [34]:
print(classification_report(y_test, y_pred_knn))

              precision    recall  f1-score   support

           0       0.84      0.81      0.82       109
           1       0.71      0.75      0.73        69

    accuracy                           0.79       178
   macro avg       0.78      0.78      0.78       178
weighted avg       0.79      0.79      0.79       178



###Naive-Bayes Algorithm

In [25]:
from sklearn.naive_bayes import GaussianNB

In [26]:
NB_model = GaussianNB()
NB_model.fit(X_train_scaled, y_train)

GaussianNB()

In [27]:
y_pred_NB = NB_model.predict(X_test_scaled)

In [29]:
accuracy_score(y_test,y_pred_NB)

0.7640449438202247

In [30]:
confusion_matrix(y_test, y_pred_NB)

array([[91, 18],
       [24, 45]])

In [32]:
print(classification_report(y_test, y_pred_NB))

              precision    recall  f1-score   support

           0       0.79      0.83      0.81       109
           1       0.71      0.65      0.68        69

    accuracy                           0.76       178
   macro avg       0.75      0.74      0.75       178
weighted avg       0.76      0.76      0.76       178



###Decission-Tree Algorithm

In [35]:
from sklearn import tree


In [36]:
tree_model = tree.DecisionTreeClassifier()
tree_model.fit(X_train_scaled, y_train)

DecisionTreeClassifier()

In [37]:
y_pred_tree = tree_model.predict(X_test_scaled)

In [38]:
accuracy_score(y_test,y_pred_tree)

0.7752808988764045

In [39]:
confusion_matrix(y_test, y_pred_tree)

array([[90, 19],
       [21, 48]])

In [40]:
print(classification_report(y_test, y_pred_tree))

              precision    recall  f1-score   support

           0       0.81      0.83      0.82       109
           1       0.72      0.70      0.71        69

    accuracy                           0.78       178
   macro avg       0.76      0.76      0.76       178
weighted avg       0.77      0.78      0.77       178



###SVM (Support Vector Machines)

In [41]:
from sklearn import svm


In [42]:
svm_model = svm.SVC()
svm_model.fit(X_train_scaled, y_train)

SVC()

In [43]:
y_pred_svm = svm_model.predict(X_test_scaled)

In [44]:
accuracy_score(y_test,y_pred_svm)

0.8314606741573034

In [45]:
confusion_matrix(y_test, y_pred_svm)

array([[96, 13],
       [17, 52]])

In [46]:
print(classification_report(y_test, y_pred_svm))

              precision    recall  f1-score   support

           0       0.85      0.88      0.86       109
           1       0.80      0.75      0.78        69

    accuracy                           0.83       178
   macro avg       0.82      0.82      0.82       178
weighted avg       0.83      0.83      0.83       178

